### ISSUE TITLE
Peatio to support admin approved withdrawals 

### ISSUE THREAD

**Issue by NQA1** [openware/peatio#1011]
Peatio to support admin approved withdrawals
At the moment, all withdrawals are automated as peatio waits for Bitgo to return a result instantaneously. If Bitgo doesn't return a result, the withdrawal is considered failed.

In prod, all withdrawals will need to be manually approved by an admin.

1. Peatio to disable logic to check for instantaneous Bitgo reply.
2. Disable Peatio daemons for Bitgo withdrawal status update.
3. Bitgo to provide a hook to inform peatio that a withdrawal is successful
4. Peatio to update the DB that the withdrawal is succesful.

**Comment by yivo** [comment]
@NQA1 Can you please fix English errors in the issue title?

**Comment by yivo** [comment]
About the steps:
1. It is normal that BitGo returns TXID immediately
2. We don't have such daemons
3. Webhooks are not safe for production use
4. This probably needs to be coded, we need to check actual status for withdraw in blockchain

This task is VERY big and breaks many logics on Peatio so it needs strong discussion. The task is not clear to me.

The current implementation allows to set quick_withdraw_limit so all withdraws must be confirmed manually (set to zero).

**Comment by yivo** [comment]
@NQA1 ping

**Comment by Sambusik** [comment]
BitGo's fees eats all the fees Peatio charges clients for trades. So Bitgo is not an ideal solution.

The default out of the box features of Peatio, is to setup the Bitcoin Core (for BTC) node and set up the default wallet. The problem is with that Hot wallet, it is not difficult to fetch the wallet.dat file from that BTC node server. To make matters worse, the wallet can't even be encrypted, since Peatio will not be able to generate new addresses for clients nor have the ability to do withdrawals anymore if the wallet is encrypted.

The other solution is not to have Hot wallets at all, and **generate the addresses offline** with a multi-sig wallet, and store these offline generated addresses in Peatio in order to provide each client with an address when they would like to do a deposit _(this has to be done every time the number of available addresses get low)_. Withdrawals now also have to be manual _(extract the list of (address,value) as csv file to import into the wallet)_, and keeping track of which in the list in the Peatio Admin got withdrawn can be a nuisance, a workaround is to provide that list with the transaction id of the actual withdrawal from the multi-sig wallet.

Has anybody come up with a better solution? _(better as in more streamlined & still remaining secure)_

**Comment by mod** [comment]
Hi @Sambusik I have a ready made solution
1- We have ready to go crypto-full node VM disk image for deployment
2- We have a pattern to extract crypto withdrawal process out of the cluster

> Peatio would have only read only access to blockchain nodes
> Peatio would publish event of withdrawal request signed and approved with 2FA
> A daemon in an isolated network, with no public IP will pop message and verify signature of barong, applogic and peatio.
> The Daemon (Cashier) have access to passphrase to decrypt wallet private keys stored in vault or better
> Daemon submit signed order to full nodes

This deserve a drawing.

In a nutshell : 
- Not a single sensitive secret in the entire kubernetes cluster
- an isolated high-security network with a withdraw executor which access either full-nodes either use wallet libraries to sign transactions.

I am not yet able to define the pop mechanism and protocol for the withdraw executor to access the queue of withdraw request.

**Comment by yivo** [comment]
Moved to #1325.
