### ISSUE TITLE
eth and erc20 payment address problem

### ISSUE THREAD

**Issue by wuminzhe** [openware/peatio#1043]
First problem I found is the eth and erc20 withdrawal's "from" address is the user's deposit address. This will fail when the user has no deposit.

Another problem is that the system generate different  eth and erc20 token addresses for one member. Ethereum is not utxo model. When the user withdraw a large amount, you need to sweep tokens to a exchange address when there is no enough eth or erc20 tokens in user's payment address. 
If the addresses of eth and erc20 is the same, this will be easier.

**Comment by yivo** [comment]
Hi @wuminzhe 

> First problem I found is the eth and erc20 withdrawal's "from" address is the user's deposit address. This will fail when the user has no deposit.

This is normal behaviour. User needs to make a deposit first.

> Another problem is that the system generate different eth and erc20 token addresses for one member. Ethereum is not utxo model. When the user withdraw a large amount, you need to sweep tokens to a exchange address when there is no enough eth or erc20 tokens in user's payment address.
If the addresses of eth and erc20 is the same, this will be easier.

The current implementation requires ETH to be present on ERC20 address. Maybe in far far future we will do similar implementation. I don't like this behavior because 1) hard to sync balance and history; 2) too many configs, again; 3) unnecessary overlinking between currencies (they must be independent).

**Comment by yivo** [comment]
So for now user must understand the ETH balance on ERC20 address and use it correctly.

**Comment by wuminzhe** [comment]
@yivo 
"User needs to make a deposit first." 
There is a problem. For example, if a user deposit eth and buy some snt with his eth. If the user never deposit snt and want to withdraw snt, it's sure to fail.

**Comment by yivo** [comment]
@wuminzhe If user never deposited SNT he is not permitted to make a withdraw.
