### ISSUE TITLE
API - trades, when getting trades list, side is null

### ISSUE THREAD

**Issue by TasyaBykova** [openware/peatio#1052]
**Steps to reproduce:** 
1. Send a get request to : https://platform.qa.etorox.io/api/v2/trades?market=ltcbtc (insert a market that there are trades for it).
2. Observer the 'side' in all the trades

**Actual result:** 'side' is null in all trades and all markets.
**Expected result:** side should appear
![image](https://user-images.githubusercontent.com/26905573/39711071-483c9de8-5227-11e8-9abc-88c4b9d4e2e4.png)

**Comment by yivo** [comment]
@TasyaBykova Side is only available in `/trades/my` because it defined the relation of trade for the specified member, e.g. I am buyer in this trade, or I am seller. `/trades` doesn't filter by member. 

![image](https://user-images.githubusercontent.com/7421323/39826107-4b6db920-53bc-11e8-87cf-e69bca362107.png)

Not a bug. Closed.
