### ISSUE TITLE
API - Orders, when there are insufficient funds in the wallet, a wrong error message appears

### ISSUE THREAD

**Issue by TasyaBykova** [openware/peatio#1078]
**Steps to reproduce:** 
Create a post call to the attached url with any coin you do not have the funds to buy for example in admin@etorox.io / 12346578 , ethusd.

Error:
"error":

{ "code": 2002, "message": "Failed to create order. Reason: cannot lock funds (amount: 0.0004)" }

**Actual result:** the error text is incorrect, see screenshot

![image](https://user-images.githubusercontent.com/26905573/39913795-d1ecab28-550b-11e8-842a-fec95d6b7e3d.png)

**Expected result:** a more accurate error should appear: 

"Order rejection. Insufficient funds in the account.
Please deposit more funds by clicking here
or decrease the order quantity. The word *here *should be a link to the deposit page"

**Comment by yivo** [comment]
@TasyaBykova This is Peatio API endpoint. Thing of Peatio like microservice. It will never include any human readable information. This should be implemented in AppLogic. We recently removed reason from error text because it exposes important information about Peatio which is security problem. Please, don't submit issues like these. We are looking to make Peatio bug-free, not include cool human-readable messages.

**Comment by yivo** [comment]
Also Peatio known nothing about frontend and AppLogic. So I believe you vision is not correct.
