### ISSUE TITLE
admin/deposits/btc URL give error when run in production using passenger and nginx

### ISSUE THREAD

**Issue by HafeezRai** [openware/peatio#1363]
When i run in production admin/deposits/btc URL give error when run in production using passenger and nginx
i have got following error log in nginx logs
NoMethodError (undefined method `end_with?' for nil:NilClass):
App 29004 output:   app/routers/crud_router.rb:19:in `action'
App 29004 output:   app/routers/admin_deposits_router.rb:9:in `call'

can anyone help in this regard while this work fine when run using puma

**Comment by yivo** [comment]
For some reasons Passenger doesn'set REQUEST_PATH. I suggest to use Puma and Docker deployment. Passenger isn't supported.

**Comment by HafeezRai** [comment]
But i am getting this error on puma 
undefined method `email' for nil:NilClass

13 14 15 16 17 18 | <% end %>     <% t.column 'Member email' do \|x\| %>       <%= link_to x.member.email, url_for([:admin, x.member]), target: '_blank' %>     <% end %>     <% t.column :amount do \|x\| %>       <code class="text-info"><%= x.amount %></code>
-- | --

**Comment by prashantomer** [comment]
Hi,
I fixed it
In `app/routers/crud_router.rb`
replace the `env['REQUEST_PATH']` with `env['REQUEST_URI']`

**Comment by AnythingLinux** [comment]
@prashantomer no your steps not help me to fixed! 

I was struggling with a similar type of problem and found that by changing config.consider_all_requests_local to true in config/environments/production.rb, I could get the error message to display in production and see what the actual problem was. Obviously, change it back once you've fixed the problem.

**Comment by AnkitRathore175** [comment]
@prashantomer 
it worked for me, thanks
