### ISSUE TITLE
Add ability to handle scopes from api keys

### ISSUE THREAD

**Issue by tamadamas** [openware/peatio#1432]
In Barong we have dynamic scopes.

Point of scopes:
User can implement a finance bot that can monitor monthly budget.
But bot should be ably only read trades and other actions should be prohibited.
We should think of other scopes, implement it and add documentation how to use it.

Related Barong issue is https://github.com/rubykube/barong/issues/540

**Comment by sramsden** [comment]
Just FYI .. I was able to implement scopes by utilising the declared scopes on the grape api.
It requires no change at all to barong.  However, you may be wanting to do something completely different so that's why I'm adding this simply as FYI.

![image](https://user-images.githubusercontent.com/8897694/43697215-f3bb9bba-9985-11e8-82e9-8b849e6c4a8c.png)

![image](https://user-images.githubusercontent.com/8897694/43697230-21c53624-9986-11e8-86bb-15bb0c615658.png)
