### ISSUE TITLE
When will there be specific instructions on authz-dummy and ambassador?

### ISSUE THREAD

**Issue by huuhait** [openware/peatio#1872]
When will there be specific instructions on authz-dummy and ambassador?
thanks Rubykube team

**Comment by huuhait** [comment]
Where is the current version deleted oauth so it will be replaced by something?

**Comment by ysv** [comment]
@Thedabest we will support only JWT authorization in peatio because using two different protocols for authentication is totally wrong.
What do you mean by asking `When will there be specific instructions on authz-dummy and ambassador`.
authz-dummy is just example for development. For stage and production you need to use Barong

**Comment by huuhait** [comment]
> @Thedabest we will support only JWT authorization in peatio because using two different protocols for authentication is totally wrong.
> What do you mean by asking `When will there be specific instructions on authz-dummy and ambassador`.
> authz-dummy is just example for development. For stage and production you need to use Barong

just that i do not know how to install barong for peatio because apigate has deleted it ...
