### ISSUE TITLE
How can we test the throughput of Peatio trading engine? 

### ISSUE THREAD

**Issue by not-a-dev0** [openware/peatio#2004]
How can we test the throughput of Peatio trading engine?  We want to test and see how many transactions per second it can handle. For example Binance can handle 1.5 Million Transactions per Second.

**Comment by ysv** [comment]
@not-a-dev0 depends on what exactly you want to test
If you want to test whole scenario starting from order creation via API and finish with trade execution you can use [stress-trading](https://github.com/rubykube/toolbox/blob/master/bin/stress_trading)

Otherwise you could experiment with spec/trading/matching

**Comment by not-a-dev0** [comment]
@ysv Thanks bud. Figured it out already.
