### ISSUE TITLE
key not found: "TIMEZONE" (KeyError)

### ISSUE THREAD

**Issue by AnythingLinux** [openware/peatio#2197]
How to fix? 

root@back:~/peatio-1.9.23# ruby -v
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
root@back:~/peatio-1.9.23# rails -v
Rails 4.2.11.1
root@back:~/peatio-1.9.23# bundle exec rails server -b 0.0.0.0
Traceback (most recent call last):
	11: from bin/rails:8:in `<main>'
	10: from bin/rails:8:in `require'
	 9: from /usr/local/rvm/gems/ruby-2.5.3/gems/railties-4.2.11.1/lib/rails/commands.rb:17:in `<top (required)>'
	 8: from /usr/local/rvm/gems/ruby-2.5.3/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	 7: from /usr/local/rvm/gems/ruby-2.5.3/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:75:in `server'
	 6: from /usr/local/rvm/gems/ruby-2.5.3/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
	 5: from /usr/local/rvm/gems/ruby-2.5.3/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:78:in `block in server'
	 4: from /usr/local/rvm/gems/ruby-2.5.3/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:78:in `require'
	 3: from /root/peatio-1.9.23/config/application.rb:17:in `<top (required)>'
	 2: from /root/peatio-1.9.23/config/application.rb:18:in `<module:Peatio>'
	 1: from /root/peatio-1.9.23/config/application.rb:35:in `<class:Application>'
/root/peatio-1.9.23/config/application.rb:35:in `fetch': key not found: "TIMEZONE" (KeyError)
root@back:~/peatio-1.9.23# 
![Screenshot from 2019-05-05 14-36-32](https://user-images.githubusercontent.com/1058663/57191062-2f62b200-6f43-11e9-8153-2d1f6a25e79f.png)

**Comment by saydulk** [comment]
root@back:~/peatio-1.9.23# ruby -v
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
root@back:~/peatio-1.9.23# rails -v
Rails 4.2.11.1
root@back:~/peatio-1.9.23# bundle exec rails server -b 0.0.0.0
Traceback (most recent call last):
	11: from bin/rails:8:in `<main>'
	10: from bin/rails:8:in `require'
	 9: from /usr/local/rvm/gems/ruby-2.5.3/gems/railties-4.2.11.1/lib/rails/commands.rb:17:in `<top (required)>'
	 8: from /usr/local/rvm/gems/ruby-2.5.3/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	 7: from /usr/local/rvm/gems/ruby-2.5.3/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:75:in `server'
	 6: from /usr/local/rvm/gems/ruby-2.5.3/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
	 5: from /usr/local/rvm/gems/ruby-2.5.3/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:78:in `block in server'
	 4: from /usr/local/rvm/gems/ruby-2.5.3/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:78:in `require'
	 3: from /root/peatio-1.9.23/config/application.rb:17:in `<top (required)>'
	 2: from /root/peatio-1.9.23/config/application.rb:18:in `<module:Peatio>'
	 1: from /root/peatio-1.9.23/config/application.rb:35:in `<class:Application>'
/root/peatio-1.9.23/config/application.rb:35:in `fetch': key not found: "TIMEZONE" (KeyError)
root@back:~/peatio-1.9.23#

**Comment by ruiandrada** [comment]
From Peatio README:

## Things You Should Know

**RUNNING AN EXCHANGE IS HARD.**

This repository is not a turn key solution and will require engineering and design of security process by your company, with or without our assistance. This repository is one component among many we recommend using for composing an enterprise grade exchange. It is highly recommended to deploy a UAT environment and build automated tests for your needs, including Functional tests, Smoke tests and Security vulnerability scans. You may not need to have an active developer on Peatio source code, however, we recommend the following team setup: 1 dev/ops, 3 frontend developers (react / angular), 2 QA engineers, 1 Security Officer.

**SECURITY KNOWLEDGE IS A REQUIREMENT.**

Peatio cannot protect your customers if you leave your admin password 1234567, or open sensitive ports to public internet. No one can. Running an exchange is a very risky task because you're dealing with money directly. If you don't know how to make your exchange secure, hire an expert.

You must know what you're doing, there's no shortcut. Please get prepared before you continue:

* Rails knowledge
* Security knowledge
* Cloud and Linux administration
* Docker and Kubernetes administration
* Micro-services and OAuth 2.0

Maybe you should ask questions here: https://discuss.rubykube.io/
