### ISSUE TITLE
Is there an easier way to add new coins?

### ISSUE THREAD

**Issue by ryanisab** [openware/peatio#284]
Looking through this codebase I found that adding ripple touched 45 files:

https://github.com/rubykube/peatio/commit/00cbf1d04ec3234f1bf6bafcbfb1304adb52f9cc

Is there an easier way to add coins to this project?

Could this project be refactored so that you add coins by just installing a new gem?

**Comment by dmk** [comment]
Hello @ryanisab!

This patch was made to support Ripple in Peatio asap, it's definitely not a good way to add a new coin (the problem is that the old Peatio was supporting only BTC and it's forks).

In the next versions we will have more generic and clean way to configure and add new currencies. You're right, adding the new currency is going to be as easy as adding a gem :wink:

**Comment by yivo** [comment]
@ryanisab I hope your issue is resolved. You may reopen it if your have any extra questions.
