### ISSUE TITLE
Create configuration variables which should be used to specify active OAuth providers

### ISSUE THREAD

**Issue by yivo** [openware/peatio#299]

**Comment by yivo** [comment]
We need to add ENV variable which is used to specify active OAuth providers:

`ENV['OAUTH2_SIGN_IN_PROVIDERS'] = 'google,auth0'`.

Put this var by default in dev section and add docs.

Remove `GOOGLE_OAUTH2_SIGN_IN` & `AUTH0_OAUTH2_SIGN_IN`.

**Comment by yivo** [comment]
Also update views.

**Comment by ysv** [comment]
I found one more mistake here
We need to use `google` as provider instead of `google_oauth2` because it will concatanate `"GOOGLE_OAUTH2_OAUTH2_REDIRECT_URL"` instead of `"GOOGLE_OAUTH2_REDIRECT_URL"` in this line of code 
https://github.com/rubykube/peatio/blob/58d7309d4540170c920b573c40062c328fc9e604/app/controllers/sessions_controller.rb#L34

**Comment by yivo** [comment]
Closed in #357.
