### ISSUE TITLE
Missing raven-js

### ISSUE THREAD

**Issue by CombatCode** [openware/peatio#323]
After fresh installation raven-js is missing:
```
ActionView::Template::Error (couldn't find file 'yarn_components/raven-js/dist/raven' with type 'application/javascript'
```
Anyway why it's stored in `yarn_components` instead of `node_modules`?

**Comment by yivo** [comment]
Hello @CombatCode 

It is not included in the project. Run `bundle exec rake yarn:install`. You can read about Yarn [here](https://yarnpkg.com/en/).

**Comment by CombatCode** [comment]
@yivo yeach, I know what it is but dunno why my issue was closed when peatio installation is still broken and `yarn_components/raven-js/dist/raven` is wrong defined path

**Comment by yivo** [comment]
@CombatCode Peatio isn't broken. `rake yarn:install` will install dependencies into `vendor/assets/yarn_components/yarn_components`. 

* `yarn_components` was chosen because Yarn itself was developed as a replacement for Bower. Bower used `bower_components` for installing deps. For me it is logical.
* `yarn_components` lives in another `yarn_components` because it prevents the same assets from relinking their versions. Sorry, this is not trivial to describe in words (ask me if you are interested).
* The reason it was placed into vendor is that Sprockets will automatically add `vendor/assets/yarn_components` to `Rails.application.config.assets.paths` so `yarn_components/raven-js/dist/raven` becomes logical path to `vendor/assets/yarn_components/yarn_components/raven-js/dist/raven`.

I am sorry you caught this trouble. It was caused due to outdated docs. We will try to update the docs along with 0.2.5 release on the next week. Now you can read Dockerfile & travis.yml to understand how to get Peatio running.

**Comment by CombatCode** [comment]
That was a while ago, so I'm not sure right now but probably docker image was not contain `rake yarn:install` and that was the beginning of the all issues. Thank you for the explanation
