### ISSUE TITLE
Add support for ERC20

### ISSUE THREAD

**Issue by mkuvsh** [openware/peatio#384]

**Comment by yivo** [comment]
We need ability to add ERC20-compatible currencies to Peatio. Basically work is mostly concentrated over `CoinAPI::ERC20`.

**Comment by dinesh-skyach** [comment]
Hi @yivo 

I have figure out the JSON-RPC methods to transfer ERC20 Tokens from one address to other. I have two approaches to achieve this functionality. Here are the following Approaches:-

**To Have Common Address For Ethereum and ERC20 Tokens**:-  ERC20 Tokens can be saved within the same Ethereum Address, So here we can use the same Ethereum address to save ERC20 Token balances.In Addition to Deposit/Withdraw ERC20 Tokens we need some ether in the address i.e Ethereum Address should have some ether for the transaction to run successfully. Here the issue arises when using the same address is that,  we use Address field as a Primary Key to identify Payment Address Record for a Member Account,  which will conflict current functionality. Also if the address is same then the Incoming/Outgoing transaction will always update the first matched address, as we Identify the Account via Address field.

**To Have Different Address For Ethereum and ERC20 Tokens**:- Here if we have different address for each ERC20 Tokens and Ethereum Accounts then we will have to add Ether to all ERC20 Tokens so that transaction can occur successfully. With this approach user have to keep some ether on all ERC20 Addresses.Ideally we should have common address for Ethereum and ERC20 Tokens. So I believe First Approach is the best way to achieve this. But Again this will conflict the current functionality.

Let me know your thoughts on this

**Comment by proactive-dev** [comment]
@vadshalamov  Hi, How are you. i've checked your ERC20 branch. Is it working? Let me know status.

**Comment by ghost** [comment]
@yivo Is it finish?

**Comment by yivo** [comment]
Closed via #913.
