### ISSUE TITLE
Regular sign/signup is not implemented?

### ISSUE THREAD

**Issue by dutchakdev** [openware/peatio#571]
Regular sign/signup is not implemented? rubykube/peatio used only oauth?

**Comment by Sambusik** [comment]
supposedly rubykube/barong would have been implemented. 
I haven't fetched from repo in a while, seems like Barong has not been integrated yet.

**Comment by yivo** [comment]
Hi @dutchakdev @Sambusik 

E-Mail sign in / sign up has been stripped from Peatio. Consider using Barong. It is integrated already.

**Comment by sosospicy** [comment]
@yivo  Sorry but I can't figure out how to make barong work with peatio.
Since it's integrated, I don't have to clone and install barong as a independent service, right?
I set 'OAUTH2_SIGN_IN_PROVIDER' to 'barong', but I don't know how to set these variables : 
  # Development configuration variables for sign in with Barong
    BARONG_CLIENT_ID:           ~
    BARONG_CLIENT_SECRET:       ~
    BARONG_DOMAIN:              ~

I read https://github.com/rubykube/omniauth-barong  but found nothing about barong client id & secret generation.    Did I miss anything?

Hope some help, and really thanks for your work!

**Comment by ghost** [comment]
https://github.com/rubykube/workbench helps.
Didn't know how to sign in with barong until I read it.
