### ISSUE TITLE
Trade page is blank

### ISSUE THREAD

**Issue by sharmaabhishek2207** [openware/peatio#742]
I am not able to see any market feed or graph on my Trade screen. Can someone please help me how to receive the latest market feed and populate on trade screen.
![trades](https://user-images.githubusercontent.com/15141642/37872991-e0ef5b66-3030-11e8-903f-e9c52166ef00.png)

**Comment by yivo** [comment]
Please, check https://github.com/rubykube/peatio/issues/738

**Comment by sharmaabhishek2207** [comment]
Thanks for the reply Yivo. I was able to setup peatio-trading-ui but don't have any clue how trade module works. Is there any third party feed which is used to get latest price of BTC and other currencies to populate on trade screen? Please help me to make it work.

**Comment by AddzMDev** [comment]
After read @yivo [link](https://github.com/rubykube/peatio/blob/master/docs/releases/1.5.0.md) above I've found the information that said

> The trading UI app will first download variables for specified market_id (like btcusd) from Peatio by issuing HTTP GET https://peatio.io/markets/btcusd.json, and then render Rails views according to received variables.

then is this occur because the link to [https://peatio.io/markets/btcusd.json](https://peatio.io/markets/btcusd.json) is invalid, but I'm still not sure whether this link should be link to [https://peatio.io/markets/btcusd.json](https://peatio.io/markets/btcusd.json) or to http://localhost:3000/markets/btcusd.json if to http://localhost:3000/markets/btcusd.json I've found that all data of each market contain only zero value like 

```
"markets": [
  {
    "id":"btcusd",
    "name":"BTC/USD",
    "quote_unit":"usd",
    "base_unit":"btc",
    "ticker":{
      "low":"0.0",
      "high":"0.0",
      "last":"0.0",
      "volume":"0.0",
      "open":"0.0",
      "sell":"0.0",
      "buy":"0.0",
      "at":1522224522
    }
  },
  {
    "id":"xrpusd",
    "name":"XRP/USD",
    "quote_unit":"usd",
    "base_unit":"xrp",
    "ticker": {
      "low":"0.0",
      "high":"0.0",
      "last":"0.0",
      "volume":"0.0",
      "open":"0.0",
      "sell":"0.0",
      "buy":"0.0",
      "at":1522224522
    }
  },
  ....,
  ..,
  .,
]
```
